language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'  
install: npm install
services:
  - mysql
before_install:
  - mysql -u root --password="" < test/sql/travis.sql
script: npm test