language: node_js
node_js:
  - 'stable'
dist: trusty
install: yarn install
services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE certifiedbev_test;'
  - mysql -u root -e "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev';"
  - mysql -u root -e "GRANT ALL ON certifiedbev_test.* TO 'dev'@'localhost';"
  - mysql -u root -e 'USE certifiedbev_test;'  
  - mysql -u root --password="" < tests/sql/travis.sql
script: yarn test

