language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'  
install: yarn install
services:
  - mysql
before_script:
  - mysql -u root --password="" < tests/sql/travis.sql
script: yarn test