language: node_js
node_js:
  - 'stable'
dist: trusty
install: yarn install
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root --password="" < tests/sql/travis.sql
script: yarn test

