language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'  
install: yarn install
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade

  # create ssl/rsa files for mysql ssl support
  - "sudo mysql_ssl_rsa_setup --uid=mysql"
  # stop mysql and use row-based format binlog
  - "sudo service mysql stop || true"
  - "echo '[mysqld]'            | sudo tee /etc/mysql/conf.d/replication.cnf"
  - "echo 'server-id=1'         | sudo tee -a /etc/mysql/conf.d/replication.cnf"
  - "echo 'log-bin=mysql'       | sudo tee -a /etc/mysql/conf.d/replication.cnf"
  - "echo 'binlog-format = row' | sudo tee -a /etc/mysql/conf.d/replication.cnf"
  - "echo 'gtid-mode = ON'      | sudo tee -a /etc/mysql/conf.d/replication.cnf"
  - "echo 'enforce_gtid_consistency = ON' | sudo tee -a /etc/mysql/conf.d/replication.cnf"

  # Start mysql (avoid errors to have logs)
  - "sudo service mysql start || true"
  - "sudo tail -1000 /var/log/syslog"  
  - mysql -u root --password="" < tests/sql/travis.sql
script: yarn test